# Generated by Django 4.2.9 on 2024-01-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='2022-03-18'),
            preserve_default=False,
        ),
    ]
